#!/usr/bin/env bash
# script to limit the nginx space
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
